fileVersion: 1
id: "10"
mappingDefinitions:
  SAMPLE_SRC:
    database: ""
    schema: ""
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  TARGET:
    database: COALESCE_DB
    schema: DEV_SCHEMA
  TEST_SRC:
    database: TEST_DB
    schema: TEST_SCHEMA
name: Prod
type: Environment
